### PR TITLE
add model for 11.0.0-ce.0

### PR DESCRIPTION
**Pull request by cyrosy**
Follow up #47 :
The 10.5 model is not working for GitLab CE >= 11.0, so I extracted the model.
After some quick tests, seems to work well with 11.0, 11.1 and 11.2.
The 10.5 model seems valid up to 10.8

### CODE REVIEW

**Comment by glensc** [comment]
how did you made the patch? did you need to apply local fixes too like in https://github.com/tracboat/tracboat/pull/36 ?

**Comment by glensc** [comment]
can you also add the information to readme?

**Comment by cyrosy** [comment]
I generated the model with the script `model-generate.sh` in your own fork, and manually applied the workaround for cyclic reference and duplicated `users_updated_by_set` relation name.
I'll update the readme tomorrow

**Comment by glensc** [comment]
ok. just leave that information in commit message, so i don't have to go and verify all that.

**Comment by cyrosy** [comment]
I updated my commit message to reflect this
I'm working on the Readme update, do you think a compatibility table between exported models and Gitlab version would do it ?

**Comment by glensc** [comment]
yeah. table seems good idea.

**Comment by cyrosy** [comment]
Seems like my table broke the layout - I'll fix this before you review it

**Comment by cyrosy** [comment]
All fixed !
If you know of any older model compatibility, update the table : I only specified the versions I tested from 10.8 to 11.2, and the two version that already were in the readme

**Comment by glensc** [comment]
i think older models should be dropped. they do not work with rest of the code.

**Comment by glensc** [comment]
this looks good. thank you for your efforts!

**Pull request merged**
